# -*- coding: utf-8 -*-
"""sentimetal-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHaFEWlQeabfvbyfsbLOYIqg6VApon0Z
"""

!pip install 'transformers[torch]'

from transformers import pipeline

# This will automatically download a default model for sentiment analysis
classifier = pipeline("sentiment-analysis")

result = classifier("I love learning about machine learning!")
print(result)

result = classifier("I  the game")
print(result)

reviews = [
  "The interface is incredibly intuitive and I love the new dark mode theme.",
  "I am extremely disappointed with the slow response times of the customer support team.",
  "The package arrived today at 3:00 PM as scheduled.",
  "This is the best purchase I have made all year; it exceeded all my expectations!",
  "I hate how the application crashes every time I try to upload a high-resolution image.",
  "The weather in London is currently cloudy with a slight chance of rain later today.",
  "Oh great, another update that breaks more features than it actually fixes.",
  "The customer service representative was polite, but they ultimately couldn't solve my problem.",
  "I'm feeling quite indifferent about the new design; it's neither better nor worse than the old one.",
  "Warning: This product contains chemicals known to cause irritation if handled without gloves.",
  "The film was a cinematic masterpiece with breathtaking visuals and a gripping storyline.",
  "I wouldn't recommend this restaurant to my worst enemy; the food was cold and the staff was rude.",
  "To reset your password, please click the link sent to your registered email address.",
  "The battery life is decent, but for this price point, I expected it to last much longer.",
  "Absolutely phenomenal service! I will definitely be coming back again next week."
]

for review in reviews:
  print(classifier(review))

result = classifier("I killed the game")
print(result)

"""### Sentiment Analysis Class

Below is a Python class `SentimentAnalyzer` that encapsulates the sentiment analysis functionality. This makes it easier to reuse the sentiment analysis model without re-initializing it every time you want to analyze a new text. It uses the `pipeline` from the `transformers` library.  

Start with installation.

`pip install 'transformers[torch]'`


"""

from transformers import pipeline

class SentimentAnalyzer:
    """
    A class to perform sentiment analysis on text(s) using the Hugging Face transformers library.

    The class initializes a sentiment-analysis pipeline upon instantiation, which downloads
    a default pre-trained model (typically `distilbert-base-uncased-finetuned-sst-2-english`)
    if one is not specified or already cached.
    """

    def __init__(self):
        """
        Initializes the SentimentAnalyzer by setting up the sentiment analysis pipeline.
        The pipeline automatically loads a suitable model for sentiment analysis.
        """
        print("Initializing Sentiment Analysis pipeline...")
        # This will automatically download a default model for sentiment analysis
        # (e.g., distilbert-base-uncased-finetuned-sst-2-english) if not already present.
        self.classifier = pipeline("sentiment-analysis")
        print("Sentiment Analysis pipeline initialized.")

    def analyze_sentiment(self, texts):
        """
        Analyzes the sentiment of one or more given texts.

        Args:
            texts (str or list[str]): A single string or a list of strings
                                     to be analyzed for sentiment.

        Returns:
            list[dict]: A list of dictionaries, where each dictionary contains
                        the 'label' (e.g., 'POSITIVE', 'NEGATIVE') and 'score'
                        for the sentiment of the corresponding input text.

        Example:
            >>> analyzer = SentimentAnalyzer()
            >>> analyzer.analyze_sentiment("I love this product!")
            #[{'label': 'POSITIVE', 'score': 0.999...}]

            >>> analyzer.analyze_sentiment([
            ...     "This is a fantastic day!",
            ...     "I am quite disappointed with the service."
            ... ])
            #[{'label': 'POSITIVE', 'score': 0.999...}], [{'label': 'NEGATIVE', 'score': 0.999...}]
        """
        if isinstance(texts, str):
            # If a single string is provided, wrap it in a list for consistent processing
            return self.classifier(texts)
        elif isinstance(texts, list):
            # If a list of strings is provided, process all of them
            return self.classifier(texts)
        else:
            raise TypeError("Input 'texts' must be a string or a list of strings.")

# instanciate the class
sentiment_analyzer = SentimentAnalyzer()

# analyze the text sentiment
text = "I hate humans"
single_text_result = sentiment_analyzer.analyze_sentiment(text)
print(single_text_result)